# Generated by Django 5.2 on 2025-04-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courseCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=100)),
                ('Course_Description', models.TextField()),
                ('Course_thumbnail', models.ImageField(upload_to='course_thumbnails/')),
                ('Course_video', models.FileField(upload_to='course_videos/')),
                ('Course_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
